### ISSUE TITLE
Requires `notebook`, not listed in `setup.py`

### ISSUE THREAD

**Issue by liffiton** [bernhard-42/ssh_ipykernel#23]
This requires `notebook`, but `pip install ssh_ipykernel` does not install it.

**Comment by tomas789** [comment]
I have tried installation in clean venv on OS X with Python 3.11.0 and everything went well. Would you be able to provide details on what was your environment?

**Comment by liffiton** [comment]
Sure!  I was testing on an older CentOS distro with a custom Python build before, but I've just reproduced it in Ubuntu 22.04 as well.  Using Python 3.10.12 and a fresh venv.  I ran `pip install ssh_ipykernel`.  It did not install `notebook`.

To verify the dependency -- in the `ssh_ipykernel` package directory:
```
$ grep notebook -r
grep: __pycache__/__init__.cpython-310.pyc: binary file matches
grep: ssh_ipykernel_interrupt/__pycache__/interrupt_handler.cpython-310.pyc: binary file matches
ssh_ipykernel_interrupt/interrupt_handler.py:   5:	from notebook.base.handlers import IPythonHandler
__init__.py:  5:	from notebook.utils import url_path_join
```

And testing an import:
```
$ python
Python 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ssh_ipykernel
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/liffiton/tmp/vevvv/lib/python3.10/site-packages/ssh_ipykernel/__init__.py", line 5, in <module>
    from notebook.utils import url_path_join
ModuleNotFoundError: No module named 'notebook'
>>> 
```

**Comment by KosukeMizuno** [comment]
I met same situation with Windows10, Python3.8.9 with a newly created venv

**Comment by Gamattention** [comment]
> I have tried installation in clean venv on OS X with Python 3.11.0 and everything went well. Would you be able to provide details on what was your environment?

Have you found a solution? I'm experiencing a similar issue.

**Comment by liffiton** [comment]
> Have you found a solution? I'm experiencing a similar issue.

A simple workaround is to manually install `notebook`.  However you installed `ssh_ipykernel` (probably using `pip`), install `notebook` the same way.

**Comment by Gamattention** [comment]
> > Have you found a solution? I'm experiencing a similar issue.
> 
> A simple workaround is to manually install `notebook`. However you installed `ssh_ipykernel` (probably using `pip`), install `notebook` the same way.

I manually installed the notebook, but I'm still getting the error "No module named 'notebook.utils'". It seems that the current notebook doesn't include these components anymore. Did you manage to successfully use the ssh_ipykernel project?

**Comment by liffiton** [comment]
Ah, I don't use it currently myself, no.  But try `pip install notebook==6.5.7` to install an earlier version of notebook that still has `notebook.utils`.
